#LAMMPS INPUT FILE

#VARIABLES
variable sd equal 136529
variable ke equal 0.05

#STYLES
boundary p p p
atom_style bond
bond_style hybrid fene harmonic 
pair_style lj/cut 1.12
pair_modify shift yes

#SETTINGS
neighbor        2.0 bin
neigh_modify    every 2 delay 2 check yes

#INPUT DATA
read_data data_nonoverlap.cfg
 
special_bonds fene
bond_coeff 1 fene 30.0 1.6 1.0000 1.0000
bond_coeff 2 harmonic $(v_ke*0.9801) 1.000000
bond_coeff 3 harmonic $(v_ke*0.9025) 1.000000
bond_coeff 4 harmonic $(v_ke*0.8100) 1.000000
bond_coeff 5 harmonic $(v_ke*0.7225) 1.000000
bond_coeff 6 harmonic $(v_ke*0.6400) 1.000000
bond_coeff 7 harmonic $(v_ke*0.5625) 1.000000
bond_coeff 8 harmonic $(v_ke*0.4900) 1.000000
bond_coeff 9 harmonic $(v_ke*0.4225) 1.000000
bond_coeff 10 harmonic $(v_ke*0.3600) 1.000000
bond_coeff 11 harmonic $(v_ke*0.3025) 1.000000
bond_coeff 12 harmonic $(v_ke*0.2500) 1.000000
pair_coeff 1 1 1.0000 1.0000 1.1225 

#DYNAMICS_SETTUP
fix nve_fix all nve
fix lan_fix all langevin 1.0 1.0 1.0 ${sd}
thermo 1000
timestep 0.01

run 10000

dump 1 all custom 500 poly_wt.lammpstrj id mol type x y z

run 10000000

#END
write_data data_final.cfg nocoeff

